[build-system]
requires = [ "setuptools >= 61.0.0", "wheel >= 0.37.0"]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
skipsdist = true
  
[testenv]
deps =
    -r requirements.txt
commands = 
    pytest
    behave
"""
